local M = {}

function M.get_types()
    return {
        ada = { icon = "", color = "#F5C2E7", name = "ada" },
        apl = { icon = "⍝", color = "#CBA6F7", name = "apl" },
        asm = { icon = "", color = "#F9E2AF", name = "asm" },
        astro = { icon = "", color = "#FAB387", name = "astro" },
        awk = { icon = "", color = "#A6E3A1", name = "awk" },
        bash = { icon = "", color = "#A6E3A1", name = "bash" },
        bib = { icon = "󱉟", color = "#EBA0AC", name = "bib" },
        c = { icon = "", color = "#89B4FA", name = "c" },
        clj = { icon = "", color = "#94E2D5", name = "clj" },
        cmake = { icon = "", color = "#F38BA8", name = "cmake" },
        coffee = { icon = "", color = "#DDB6F2", name = "coffee" },
        cpp = { icon = "", color = "#B4BEFE", name = "cpp" },
        cr = { icon = "", color = "#F2CDCD", name = "cr" },
        cs = { icon = "󰌛", color = "#CBA6F7", name = "cs" },
        css = { icon = "", color = "#89B4FA", name = "css" },
        csv = { icon = "󰈛", color = "#A6E3A1", name = "csv" },
        dart = { icon = "", color = "#74C7EC", name = "dart" },
        diff = { icon = "", color = "#F9E2AF", name = "diff" },
        dockerfile = { icon = "󰡨", color = "#89DCEB", name = "dockerfile" },
        editorconfig = { icon = "", color = "#F5E0DC", name = "editorconfig" },
        eex = { icon = "", color = "#CBA6F7", name = "eex" },
        ejs = { icon = "", color = "#F9E2AF", name = "ejs" },
        elixir = { icon = "", color = "#CBA6F7", name = "elixir" },
        elm = { icon = "", color = "#74C7EC", name = "elm" },
        env = { icon = "", color = "#A6E3A1", name = "env" },
        erb = { icon = "", color = "#F38BA8", name = "erb" },
        erl = { icon = "", color = "#F38BA8", name = "erl" },
        fish = { icon = "", color = "#A6E3A1", name = "fish" },
        fs = { icon = "", color = "#74C7EC", name = "fs" },
        f90 = { icon = "󱈚", color = "#B4BEFE", name = "f90" },
        gd = { icon = "", color = "#89B4FA", name = "gd" },
        git = { icon = "", color = "#F38BA8", name = "git" },
        gleam = { icon = "󰦥", color = "#F5C2E7", name = "gleam" },
        glsl = { icon = "󱓙", color = "#89DCEB", name = "glsl" },
        go = { icon = "", color = "#94E2D5", name = "go" },
        graphql = { icon = "", color = "#F5C2E7", name = "graphql" },
        groovy = { icon = "", color = "#89DCEB", name = "groovy" },
        haml = { icon = "", color = "#F5E0DC", name = "haml" },
        hs = { icon = "", color = "#CBA6F7", name = "hs" },
        html = { icon = "", color = "#FAB387", name = "html" },
        ini = { icon = "", color = "#BAC2DE", name = "ini" },
        java = { icon = "", color = "#FAB387", name = "java" },
        jl = { icon = "", color = "#CBA6F7", name = "jl" },
        js = { icon = "", color = "#F9E2AF", name = "js" },
        json = { icon = "", color = "#F5C2E7", name = "json" },
        json5 = { icon = "", color = "#F5C2E7", name = "json5" },
        jsonc = { icon = "", color = "#F5C2E7", name = "jsonc" },
        jsx = { icon = "", color = "#89DCEB", name = "jsx" },
        kt = { icon = "", color = "#CBA6F7", name = "kt" },
        less = { icon = "", color = "#89B4FA", name = "less" },
        license = { icon = "", color = "#A6E3A1", name = "license" },
        liquid = { icon = "", color = "#89B4FA", name = "liquid" },
        lock = { icon = "󰌾", color = "#BAC2DE", name = "lock" },
        log = { icon = "󰌱", color = "#F9E2AF", name = "log" },
        lua = { icon = "", color = "#89B4FA", name = "lua" },
        luau = { icon = "", color = "#74C7EC", name = "luau" },
        makefile = { icon = "", color = "#F38BA8", name = "makefile" },
        markdown = { icon = "", color = "#89B4FA", name = "markdown" },
        mdx = { icon = "", color = "#74C7EC", name = "mdx" },
        nim = { icon = "󰆥", color = "#F9E2AF", name = "nim" },
        nix = { icon = "", color = "#89DCEB", name = "nix" },
        node_modules = { icon = "", color = "#A6E3A1", name = "node_modules" },
        obj = { icon = "󰆧", color = "#BAC2DE", name = "obj" },
        ocaml = { icon = "", color = "#FAB387", name = "ocaml" },
        odin = { icon = "󰟢", color = "#89DCEB", name = "odin" },
        org = { icon = "", color = "#89B4FA", name = "org" },
        pdf = { icon = "", color = "#F38BA8", name = "pdf" },
        php = { icon = "", color = "#CBA6F7", name = "php" },
        pl = { icon = "", color = "#74C7EC", name = "pl" },
        png = { icon = "󰈟", color = "#A6E3A1", name = "png" },
        prisma = { icon = "", color = "#89DCEB", name = "prisma" },
        ps1 = { icon = "󰨊", color = "#89B4FA", name = "ps1" },
        py = { icon = "", color = "#F9E2AF", name = "py" },
        r = { icon = "󰟔", color = "#74C7EC", name = "r" },
        rb = { icon = "", color = "#F38BA8", name = "rb" },
        rescript = { icon = "", color = "#F38BA8", name = "rescript" },
        rs = { icon = "", color = "#FAB387", name = "rs" },
        sass = { icon = "", color = "#F5C2E7", name = "sass" },
        scala = { icon = "", color = "#F38BA8", name = "scala" },
        scm = { icon = "󰘧", color = "#F9E2AF", name = "scm" },
        scss = { icon = "", color = "#F5C2E7", name = "scss" },
        sh = { icon = "", color = "#A6E3A1", name = "sh" },
        slim = { icon = "", color = "#F5E0DC", name = "slim" },
        sql = { icon = "", color = "#89DCEB", name = "sql" },
        sqlite = { icon = "", color = "#74C7EC", name = "sqlite" },
        svelte = { icon = "", color = "#FAB387", name = "svelte" },
        svg = { icon = "󰜡", color = "#F9E2AF", name = "svg" },
        swift = { icon = "", color = "#FAB387", name = "swift" },
        tcl = { icon = "󰛓", color = "#74C7EC", name = "tcl" },
        templ = { icon = "", color = "#89DCEB", name = "templ" },
        terminal = { icon = "", color = "#A6E3A1", name = "terminal" },
        tex = { icon = "󰙩", color = "#89B4FA", name = "tex" },
        toml = { icon = "", color = "#BAC2DE", name = "toml" },
        ts = { icon = "", color = "#89B4FA", name = "ts" },
        tscn = { icon = "", color = "#89B4FA", name = "tscn" },
        tsx = { icon = "", color = "#74C7EC", name = "tsx" },
        twig = { icon = "", color = "#A6E3A1", name = "twig" },
        typ = { icon = "", color = "#F9E2AF", name = "typ" },
        vala = { icon = "", color = "#74C7EC", name = "vala" },
        v = { icon = "󰍛", color = "#A6E3A1", name = "v" },
        vhd = { icon = "󰍛", color = "#CBA6F7", name = "vhd" },
        vim = { icon = "", color = "#A6E3A1", name = "vim" },
        vue = { icon = "", color = "#A6E3A1", name = "vue" },
        wasm = { icon = "", color = "#CBA6F7", name = "wasm" },
        webpack = { icon = "󰜫", color = "#89DCEB", name = "webpack" },
        xml = { icon = "󰗀", color = "#FAB387", name = "xml" },
        yaml = { icon = "", color = "#BAC2DE", name = "yaml" },
        zig = { icon = "", color = "#F9E2AF", name = "zig" },
        zsh = { icon = "", color = "#A6E3A1", name = "zsh" },
    }
end

function M.get_extensions()
    return {
        adb = "ada",
        ads = "ada",
        apl = "apl",
        dyalog = "apl",
        asm = "asm",
        s = "asm",
        astro = "astro",
        awk = "awk",
        bash = "bash",
        sh = "sh",
        zsh = "zsh",
        fish = "fish",
        bib = "bib",
        tex = "tex",
        c = "c",
        h = "c",
        clj = "clj",
        cljs = "clj",
        cljc = "clj",
        edn = "clj",
        cmake = "cmake",
        coffee = "coffee",
        cson = "coffee",
        cpp = "cpp",
        cxx = "cpp",
        cc = "cpp",
        ["c++"] = "cpp",
        hpp = "cpp",
        hxx = "cpp",
        hh = "cpp",
        cr = "cr",
        cs = "cs",
        csx = "cs",
        css = "css",
        csv = "csv",
        dart = "dart",
        diff = "diff",
        patch = "diff",
        dockerfile = "dockerfile",
        editorconfig = "editorconfig",
        ex = "elixir",
        exs = "elixir",
        eex = "eex",
        heex = "eex",
        elm = "elm",
        env = "env",
        erb = "erb",
        rhtml = "erb",
        ejs = "ejs",
        haml = "haml",
        slim = "slim",
        twig = "twig",
        erl = "erl",
        hrl = "erl",
        fs = "fs",
        fsx = "fs",
        fsi = "fs",
        f90 = "f90",
        f95 = "f90",
        f03 = "f90",
        f08 = "f90",
        ["for"] = "f90",
        f = "f90",
        gd = "gd",
        tscn = "tscn",
        git = "git",
        gleam = "gleam",
        glsl = "glsl",
        vert = "glsl",
        frag = "glsl",
        go = "go",
        gql = "graphql",
        graphql = "graphql",
        groovy = "groovy",
        gradle = "groovy",
        hs = "hs",
        lhs = "hs",
        html = "html",
        htm = "html",
        ini = "ini",
        conf = "ini",
        cfg = "ini",
        java = "java",
        class = "java",
        jl = "jl",
        js = "js",
        mjs = "js",
        cjs = "js",
        json = "json",
        json5 = "json5",
        jsonc = "jsonc",
        jsx = "jsx",
        kt = "kt",
        kts = "kt",
        less = "less",
        liquid = "liquid",
        lock = "lock",
        log = "log",
        lua = "lua",
        luau = "luau",
        md = "markdown",
        markdown = "markdown",
        mdx = "mdx",
        nim = "nim",
        nix = "nix",
        o = "obj",
        obj = "obj",
        ml = "ocaml",
        mli = "ocaml",
        odin = "odin",
        org = "org",
        pdf = "pdf",
        php = "php",
        pl = "pl",
        pm = "pl",
        png = "png",
        prisma = "prisma",
        ps1 = "ps1",
        psm1 = "ps1",
        psd1 = "ps1",
        py = "py",
        pyc = "py",
        pyd = "py",
        pyi = "py",
        r = "r",
        rb = "rb",
        rake = "rb",
        gemspec = "rb",
        res = "rescript",
        rs = "rs",
        sass = "sass",
        scss = "scss",
        scala = "scala",
        sc = "scala",
        scm = "scm",
        ss = "scm",
        sql = "sql",
        sqlite = "sqlite",
        db = "sqlite",
        svelte = "svelte",
        svg = "svg",
        swift = "swift",
        tcl = "tcl",
        templ = "templ",
        toml = "toml",
        ts = "ts",
        mts = "ts",
        cts = "ts",
        tsx = "tsx",
        typ = "typ",
        vala = "vala",
        vapi = "vala",
        v = "v",
        vhd = "vhd",
        vhdl = "vhd",
        vim = "vim",
        vue = "vue",
        wasm = "wasm",
        webpack = "webpack",
        xml = "xml",
        yaml = "yaml",
        yml = "yaml",
        zig = "zig",
    }
end

function M.get_filenames()
    return {
        [".SRCINFO"] = "ini",
        [".Xauthority"] = "ini",
        [".Xresources"] = "ini",
        [".babelrc"] = "json",
        [".bash_profile"] = "bash",
        [".bashrc"] = "bash",
        [".clang-format"] = "yaml",
        [".clang-tidy"] = "yaml",
        [".clangd"] = "yaml",
        [".codespellrc"] = "ini",
        [".condarc"] = "yaml",
        [".dockerignore"] = "dockerfile",
        [".ds_store"] = "ini",
        [".editorconfig"] = "editorconfig",
        [".env"] = "env",
        [".eslintignore"] = "git",
        [".eslintrc"] = "json",
        [".git-blame-ignore-revs"] = "git",
        [".gitattributes"] = "git",
        [".gitconfig"] = "git",
        [".gitignore"] = "git",
        [".gitlab-ci.yml"] = "yaml",
        [".gitmodules"] = "git",
        [".gtkrc-2.0"] = "ini",
        [".gvimrc"] = "vim",
        [".justfile"] = "makefile",
        [".luacheckrc"] = "lua",
        [".luaurc"] = "luau",
        [".mailmap"] = "git",
        [".nanorc"] = "ini",
        [".npmignore"] = "git",
        [".npmrc"] = "json",
        [".nuxtrc"] = "vue",
        [".nvmrc"] = "node_modules",
        [".pnpmfile.cjs"] = "js",
        [".pre-commit-config.yaml"] = "yaml",
        [".prettierignore"] = "json",
        [".prettierrc"] = "json",
        [".prettierrc.cjs"] = "js",
        [".prettierrc.js"] = "js",
        [".prettierrc.json"] = "json",
        [".prettierrc.json5"] = "json5",
        [".prettierrc.mjs"] = "js",
        [".prettierrc.toml"] = "toml",
        [".prettierrc.yaml"] = "yaml",
        [".prettierrc.yml"] = "yaml",
        [".pylintrc"] = "ini",
        [".settings.json"] = "json",
        [".vimrc"] = "vim",
        [".xinitrc"] = "sh",
        [".xsession"] = "sh",
        [".zprofile"] = "zsh",
        [".zshenv"] = "zsh",
        [".zshrc"] = "zsh",

        ["AUTHORS"] = "markdown",
        ["AUTHORS.txt"] = "markdown",
        ["Directory.Build.props"] = "xml",
        ["Directory.Build.targets"] = "xml",
        ["Directory.Packages.props"] = "xml",
        ["FreeCAD.conf"] = "ini",
        ["Gemfile"] = "rb",
        ["Jenkinsfile"] = "groovy",
        ["PKGBUILD"] = "sh",
        ["PrusaSlicer.ini"] = "ini",
        ["PrusaSlicerGcodeViewer.ini"] = "ini",
        ["QtProject.conf"] = "ini",
        ["_gvimrc"] = "vim",
        ["_vimrc"] = "vim",
        ["bitbucket-pipelines.yml"] = "yaml",
        ["brewfile"] = "rb",
        ["bspwmrc"] = "sh",
        ["build"] = "makefile",
        ["build.gradle"] = "groovy",
        ["build.zig.zon"] = "zig",
        ["bun.lock"] = "lock",
        ["bun.lockb"] = "lock",
        ["cantorrc"] = "ini",
        ["checkhealth"] = "vim",
        ["cmakelists.txt"] = "cmake",
        ["code_of_conduct"] = "markdown",
        ["code_of_conduct.md"] = "markdown",
        ["commit_editmsg"] = "git",
        ["commitlint.config.js"] = "js",
        ["commitlint.config.ts"] = "ts",
        ["compose.yaml"] = "dockerfile",
        ["compose.yml"] = "dockerfile",
        ["config"] = "ini",
        ["containerfile"] = "dockerfile",
        ["copying"] = "license",
        ["copying.lesser"] = "license",
        ["docker-compose.yaml"] = "dockerfile",
        ["docker-compose.yml"] = "dockerfile",
        ["dockerfile"] = "dockerfile",
        ["dune"] = "ocaml",
        ["eslint.config.cjs"] = "js",
        ["eslint.config.js"] = "js",
        ["eslint.config.mjs"] = "js",
        ["eslint.config.ts"] = "ts",
        ["ext_typoscript_setup.txt"] = "txt",
        ["favicon.ico"] = "png",
        ["fp-info-cache"] = "ini",
        ["fp-lib-table"] = "ini",
        ["gnumakefile"] = "makefile",
        ["go.mod"] = "go",
        ["go.sum"] = "go",
        ["go.work"] = "go",
        ["gradle-wrapper.properties"] = "ini",
        ["gradle.properties"] = "ini",
        ["gradlew"] = "sh",
        ["groovy"] = "groovy",
        ["gruntfile.babel.js"] = "js",
        ["gruntfile.coffee"] = "coffee",
        ["gruntfile.js"] = "js",
        ["gruntfile.ts"] = "ts",
        ["gtkrc"] = "ini",
        ["gulpfile.babel.js"] = "js",
        ["gulpfile.coffee"] = "coffee",
        ["gulpfile.js"] = "js",
        ["gulpfile.ts"] = "ts",
        ["hypridle.conf"] = "ini",
        ["hyprland.conf"] = "ini",
        ["hyprlandd.conf"] = "ini",
        ["hyprlock.conf"] = "ini",
        ["hyprpaper.conf"] = "ini",
        ["hyprsunset.conf"] = "ini",
        ["i18n.config.js"] = "js",
        ["i18n.config.ts"] = "ts",
        ["i3blocks.conf"] = "ini",
        ["i3status.conf"] = "ini",
        ["index.theme"] = "ini",
        ["ionic.config.json"] = "json",
        ["justfile"] = "makefile",
        ["kalgebrarc"] = "ini",
        ["kdeglobals"] = "ini",
        ["kdenlive-layoutsrc"] = "ini",
        ["kdenliverc"] = "ini",
        ["kritadisplayrc"] = "ini",
        ["kritarc"] = "ini",
        ["license"] = "license",
        ["license.md"] = "license",
        ["lxde-rc.xml"] = "xml",
        ["lxqt.conf"] = "ini",
        ["makefile"] = "makefile",
        ["mix.lock"] = "lock",
        ["mpv.conf"] = "ini",
        ["next.config.cjs"] = "js",
        ["next.config.js"] = "js",
        ["next.config.ts"] = "ts",
        ["node_modules"] = "node_modules",
        ["nuxt.config.cjs"] = "js",
        ["nuxt.config.js"] = "js",
        ["nuxt.config.mjs"] = "js",
        ["nuxt.config.ts"] = "ts",
        ["package-lock.json"] = "lock",
        ["package.json"] = "json",
        ["platformio.ini"] = "ini",
        ["playwright.config.cjs"] = "js",
        ["playwright.config.cts"] = "ts",
        ["playwright.config.js"] = "js",
        ["playwright.config.mjs"] = "js",
        ["playwright.config.mts"] = "ts",
        ["playwright.config.ts"] = "ts",
        ["pnpm-lock.yaml"] = "lock",
        ["pnpm-workspace.yaml"] = "yaml",
        ["pom.xml"] = "xml",
        ["prettier.config.cjs"] = "js",
        ["prettier.config.js"] = "js",
        ["prettier.config.mjs"] = "js",
        ["prettier.config.ts"] = "ts",
        ["prisma.config.mts"] = "prisma",
        ["prisma.config.ts"] = "prisma",
        ["procfile"] = "sh",
        ["py.typed"] = "py",
        ["rakefile"] = "rb",
        ["readme"] = "markdown",
        ["readme.md"] = "markdown",
        ["rmd"] = "markdown",
        ["robots.txt"] = "txt",
        ["security"] = "markdown",
        ["security.md"] = "markdown",
        ["settings.gradle"] = "groovy",
        ["svelte.config.js"] = "js",
        ["sxhkdrc"] = "sh",
        ["sym-lib-table"] = "ini",
        ["tailwind.config.js"] = "js",
        ["tailwind.config.mjs"] = "js",
        ["tailwind.config.ts"] = "ts",
        ["tmux.conf"] = "ini",
        ["tmux.conf.local"] = "ini",
        ["tsconfig.json"] = "json",
        ["unlicense"] = "license",
        ["vagrantfile"] = "ruby",
        ["vercel.json"] = "json",
        ["vite.config.cjs"] = "js",
        ["vite.config.cts"] = "ts",
        ["vite.config.js"] = "js",
        ["vite.config.mjs"] = "js",
        ["vite.config.mts"] = "ts",
        ["vite.config.ts"] = "ts",
        ["vitest.config.cjs"] = "js",
        ["vitest.config.cts"] = "ts",
        ["vitest.config.js"] = "js",
        ["vitest.config.mjs"] = "js",
        ["vitest.config.mts"] = "ts",
        ["vitest.config.ts"] = "ts",
        ["vlcrc"] = "ini",
        ["webpack"] = "webpack",
        ["weston.ini"] = "ini",
        ["workspace"] = "makefile",
        ["wrangler.jsonc"] = "jsonc",
        ["wrangler.toml"] = "toml",
        ["xdph.conf"] = "ini",
        ["xmobarrc"] = "hs",
        ["xmobarrc.hs"] = "hs",
        ["xmonad.hs"] = "hs",
        ["xorg.conf"] = "ini",
        ["xsettingsd.conf"] = "ini",
    }
end

return M
